apiVersion: v1
kind: Namespace
metadata:
  name: digitalocean

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: volume-10g-01
  namespace: digitalocean
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: "my-frontend"
  replicas: 2
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: my-frontend
        image: busybox
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: "/data"
          name: volume-10g-01-pvc
  volumeClaimTemplates:
  - metadata:
      name: volume-10g-01-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage 
 
 
 
 
