apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch-ingress
  namespace: opensearch
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "192.168.0.100"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensearch-lb
                port:
                  number: 9200
