
apiVersion: v1
kind: Namespace
metadata:
  name: opensearch

---

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: opensearch
#   namespace: opensearch
# spec:
#   destination:
#     namespace: opensearch
#     server: https://3763d097-d7e4-4354-9907-b03749694878.k8s.ondigitalocean.com
#   source:
#     repoURL: https://opensearch-project.github.io/helm-charts/
#     targetRevision: main
#     helm:
#       valueFiles:
#         - values.yaml
#       releaseName: my-deployment
#       chart: opensearch/opensearch
#   project: default


# apiVersion: v1
# kind: Service
# metadata:
#   name: opensearch
#   namespace: opensearch
# spec:
#   selector:
#     app: opensearch
#   ports:
#     - port: 9200
#       targetPort: 9200
#       name: http
#     # - port: 9300
#     #   targetPort: 9300
#     #   name: transport

# ---

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: opensearch
#   namespace: opensearch
# spec:
#   serviceName: opensearch
#   replicas: 1
#   selector:
#     matchLabels:
#       app: opensearch
#   template:
#     metadata:
#       labels:
#         app: opensearch
#     spec:
#       containers:
#         - name: opensearch
#           image: opensearchproject/opensearch:1.0.0
#           ports:
#             - containerPort: 9200
#               name: http
#             # - containerPort: 9300
#             #   name: transport
#           volumeMounts:
#             - name: opensearch-data
#               mountPath: /usr/share/opensearch/data
#           resources:
#             limits:
#               memory: 2Gi
#             requests:
#               memory: 2Gi
#           env:
#             - name: cluster.name
#               value: opensearch-cluster
#             - name: discovery.type
#               value: single-node
#   volumeClaimTemplates:
#     - metadata:
#         name: opensearch-data
#       spec:
#         accessModes:
#           - ReadWriteOnce
#         resources:
#           requests:
#             storage: 5Gi
            
# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: opensearch
#   namespace: opensearch
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     - host: opensearch.faceira.me
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: opensearch
#                 port:
#                   number: 9200
            
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: opensearch-dashboards
#   namespace: opensearch
# spec:
#   selector:
#     app: opensearch-dashboards
#   ports:
#     - port: 5601
#       targetPort: 5601

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: opensearch-dashboards
#   namespace: opensearch
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: opensearch-dashboards
#   template:
#     metadata:
#       labels:
#         app: opensearch-dashboards
#     spec:
#       containers:
#         - name: opensearch-dashboards
#           image: opensearchproject/opensearch-dashboards:1.0.0
#           ports:
#             - containerPort: 5601
#           env:
#             - name: ELASTICSEARCH_URL
#               value: http://opensearch:9200
              
# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: opensearch-dashboards-ingress
#   namespace: opensearch
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     - host: opensearch-dashboards.example.com
#       http:
#         paths:
#           - pathType: Prefix
#             path: /
#             backend:
#               service:
#                 name: opensearch-dashboards
#                 port:
#                   number: 5601

# ---
